<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything (treeline)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT treeline EMPTY>
	<!ATTLIST treeline id NMTOKEN #REQUIRED>
	<!ATTLIST treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST treeline expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="trakem2_ch1234_tracing_1026end_omni_05.xml"
		unuid="1545898967537.850315429.3393"
		mipmaps_folder="trakem2.1545898967537.850315429.3393/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
		<anything id="1041" expanded="true">
			<treeline id="1001" oid="1002"/>
			<treeline id="1003" oid="1004"/>
			<treeline id="1005" oid="1006"/>
			<treeline id="1007" oid="1008"/>
			<treeline id="1009" oid="1010"/>
			<treeline id="1011" oid="1012"/>
			<treeline id="1013" oid="1014"/>
			<treeline id="1015" oid="1016"/>
			<treeline id="1017" oid="1018"/>
			<treeline id="1019" oid="1020"/>
			<treeline id="1021" oid="1022"/>
			<treeline id="1023" oid="1024"/>
			<treeline id="1025" oid="1026"/>
			<treeline id="1027" oid="1028"/>
			<treeline id="1029" oid="1030"/>
			<treeline id="1031" oid="1032"/>
			<treeline id="1033" oid="1034"/>
			<treeline id="1035" oid="1036"/>
			<treeline id="1037" oid="1038"/>
			<treeline id="1039" oid="1040"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2273.0"
		layer_height="3128.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="false"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_treeline
			oid="1002"
			width="263.0"
			height="259.0"
			transform="matrix(1.0,0.0,0.0,1.0,1076.0,1283.0)"
			locked="true"
			visible="false"
			title="treeline"
			links="611,614,617,620,623,626,629,632,635,641,644,647,650,653,656,659,662,665,668,671,674,677,680,683,686,689,692,695,698,701,704,707,710,713,716,722,725"
			layer_set_id="3"
			style="fill:none;stroke-opacity:0.97;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
		>
			<t2_node x="252.90002" y="130.69995" lid="858">
			 <t2_tag name="seed" key="S" />
			<t2_node x="253.19995" y="131.09998" lid="855">
			<t2_node x="253.09998" y="130.90002" lid="852">
			<t2_node x="253.09998" y="133.19995" lid="852">
			<t2_node x="253.59998" y="133.30005" lid="849">
			<t2_node x="260.0" y="123.0" lid="849">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="253.0" y="133.0" lid="849">
			<t2_node x="252.80005" y="132.69995" lid="846">
			<t2_node x="251.90002" y="132.69995" lid="843">
			<t2_node x="252.30005" y="133.09998" lid="840">
			<t2_node x="253.0" y="139.0" lid="840">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="253.0" y="132.0" lid="840">
			<t2_node x="254.0" y="132.0" lid="840">
			<t2_node x="252.30005" y="133.5" lid="837">
			<t2_node x="251.90002" y="133.30005" lid="834">
			<t2_node x="252.30005" y="133.90002" lid="831">
			<t2_node x="260.0" y="140.0" lid="831">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="252.0" y="135.0" lid="831">
			<t2_node x="251.0" y="135.09998" lid="828">
			<t2_node x="250.80005" y="134.0" lid="825">
			<t2_node x="251.30005" y="134.59998" lid="822">
			<t2_node x="247.0" y="142.0" lid="822">
			 <t2_tag name="POm input" key="2" />
			 <t2_tag name="Large Bouton POm" key="4" />
			 </t2_node>
			<t2_node x="251.0" y="134.0" lid="822">
			<t2_node x="249.0" y="140.0" lid="822">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="251.0" y="133.0" lid="822">
			<t2_node x="250.30005" y="133.69995" lid="819">
			<t2_node x="249.80005" y="132.90002" lid="816">
			<t2_node x="249.30005" y="132.59998" lid="813">
			<t2_node x="256.0" y="134.0" lid="813">
			 <t2_tag name="M1 input" key="1" />
			 <t2_tag name="Large Bouton M1" key="3" />
			 </t2_node>
			<t2_node x="248.0" y="132.0" lid="813">
			<t2_node x="245.69995" y="132.19995" lid="810">
			<t2_node x="245.09998" y="131.90002" lid="807">
			<t2_node x="263.0" y="134.0" lid="807">
			 <t2_tag name="M1 input" key="1" />
			 <t2_tag name="Large Bouton M1" key="3" />
			 </t2_node>
			<t2_node x="245.0" y="131.0" lid="807">
			<t2_node x="245.0" y="130.0" lid="807">
			<t2_node x="245.0" y="129.90002" lid="804">
			<t2_node x="238.0" y="124.0" lid="804">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="244.0" y="131.0" lid="804">
			<t2_node x="243.0" y="131.0" lid="804">
			<t2_node x="242.80005" y="131.0" lid="801">
			<t2_node x="231.0" y="135.0" lid="801">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="243.0" y="130.0" lid="801">
			<t2_node x="243.0" y="129.0" lid="801">
			<t2_node x="244.0" y="128.0" lid="801">
			<t2_node x="244.30005" y="127.900024" lid="798">
			<t2_node x="249.0" y="119.0" lid="798">
			 <t2_tag name="POm input" key="2" />
			 </t2_node>
			<t2_node x="244.0" y="129.0" lid="798">
			<t2_node x="244.0" y="129.09998" lid="795">
			<t2_node x="257.0" y="136.0" lid="795">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="243.0" y="129.0" lid="795">
			<t2_node x="242.0" y="129.0" lid="795">
			<t2_node x="241.0" y="129.0" lid="795">
			<t2_node x="239.90002" y="128.09998" lid="792">
			<t2_node x="239.80005" y="128.80005" lid="789">
			<t2_node x="240.0" y="128.0" lid="789">
			<t2_node x="240.0" y="128.0" lid="789">
			<t2_node x="239.0" y="128.0" lid="789">
			<t2_node x="239.0" y="128.0" lid="789">
			<t2_node x="238.0" y="128.0" lid="789">
			<t2_node x="239.0" y="128.0" lid="789">
			<t2_node x="239.40002" y="128.90002" lid="786">
			<t2_node x="239.69995" y="128.90002" lid="783">
			<t2_node x="246.0" y="124.0" lid="783">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="239.0" y="129.0" lid="783">
			<t2_node x="238.0" y="129.0" lid="783">
			<t2_node x="238.0" y="130.0" lid="783">
			<t2_node x="238.30005" y="129.19995" lid="780">
			<t2_node x="237.19995" y="128.80005" lid="777">
			<t2_node x="236.69995" y="129.09998" lid="774">
			<t2_node x="249.0" y="127.0" lid="774">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="236.0" y="129.0" lid="774">
			<t2_node x="236.59998" y="129.69995" lid="771">
			<t2_node x="237.0" y="121.0" lid="771">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="235.0" y="131.0" lid="771">
			<t2_node x="233.69995" y="131.80005" lid="768">
			<t2_node x="233.90002" y="132.19995" lid="765">
			<t2_node x="243.0" y="133.0" lid="765">
			 <t2_tag name="POm input" key="2" />
			 </t2_node>
			<t2_node x="234.0" y="133.0" lid="765">
			<t2_node x="233.09998" y="132.0" lid="762">
			<t2_node x="233.40002" y="133.19995" lid="759">
			<t2_node x="234.30005" y="133.5" lid="756">
			<t2_node x="233.19995" y="132.19995" lid="753">
			<t2_node x="232.90002" y="132.19995" lid="750">
			<t2_node x="232.90002" y="131.19995" lid="747">
			<t2_node x="232.40002" y="131.0" lid="744">
			<t2_node x="223.0" y="125.0" lid="744">
			 <t2_tag name="POm input" key="2" />
			 </t2_node>
			<t2_node x="231.0" y="132.0" lid="744">
			<t2_node x="229.30005" y="132.19995" lid="741">
			<t2_node x="228.40002" y="130.40002" lid="738">
			<t2_node x="228.0" y="129.30005" lid="735">
			<t2_node x="225.69995" y="126.30005" lid="732">
			<t2_node x="225.0" y="125.5" lid="729">
			<t2_node x="224.30005" y="124.400024" lid="726">
			<t2_node x="224.30005" y="125.0" lid="723">
			<t2_node x="224.19995" y="125.400024" lid="720">
			<t2_node x="223.59998" y="123.599976" lid="717">
			<t2_node x="223.30005" y="122.5" lid="714">
			<t2_node x="224.59998" y="122.5" lid="711">
			<t2_node x="222.59998" y="122.900024" lid="708">
			<t2_node x="220.09998" y="123.599976" lid="705">
			<t2_node x="217.80005" y="124.900024" lid="702">
			<t2_node x="216.5" y="124.69995" lid="699">
			<t2_node x="215.90002" y="124.400024" lid="696">
			<t2_node x="214.30005" y="124.400024" lid="693">
			<t2_node x="214.19995" y="124.19995" lid="690">
			<t2_node x="213.30005" y="123.30005" lid="687">
			<t2_node x="212.80005" y="123.5" lid="684">
			<t2_node x="212.30005" y="120.900024" lid="681">
			<t2_node x="212.19995" y="120.69995" lid="678">
			<t2_node x="212.30005" y="121.400024" lid="675">
			<t2_node x="210.59998" y="121.0" lid="672">
			<t2_node x="210.19995" y="120.099976" lid="669">
			<t2_node x="209.80005" y="120.0" lid="666">
			<t2_node x="208.59998" y="119.400024" lid="663">
			<t2_node x="207.80005" y="118.80005" lid="660">
			<t2_node x="205.80005" y="119.400024" lid="657">
			<t2_node x="204.69995" y="119.900024" lid="654">
			<t2_node x="203.90002" y="119.099976" lid="651">
			<t2_node x="202.90002" y="118.19995" lid="648">
			<t2_node x="202.09998" y="117.900024" lid="645">
			<t2_node x="201.40002" y="117.69995" lid="642">
			 <t2_tag name="M1 input" key="1" />
			<t2_node x="200.0" y="117.099976" lid="639">
			<t2_node x="198.80005" y="116.80005" lid="636">
			<t2_node x="197.19995" y="116.599976" lid="633">
			<t2_node x="197.09998" y="116.599976" lid="630">
			<t2_node x="198.90002" y="114.900024" lid="627">
			<t2_node x="198.40002" y="114.099976" lid="624">
			<t2_node x="197.40002" y="113.900024" lid="621">
			<t2_node x="197.09998" y="115.400024" lid="618">
			<t2_node x="197.0" y="116.400024" lid="615">
			<t2_node x="198.69995" y="116.400024" lid="612">
			<t2_node x="198.09998" y="115.80005" lid="609">
			<t2_node x="198.19995" y="116.400024" lid="606">
			<t2_node x="197.40002" y="116.19995" lid="603">
			<t2_node x="197.40002" y="115.900024" lid="600">
			<t2_node x="197.69995" y="115.099976" lid="597">
			<t2_node x="197.09998" y="114.900024" lid="594">
			<t2_node x="196.69995" y="114.19995" lid="591">
			<t2_node x="195.09998" y="112.19995" lid="588">
			<t2_node x="193.0" y="111.19995" lid="582">
			<t2_node x="191.90002" y="111.400024" lid="579">
			<t2_node x="190.30005" y="111.80005" lid="576">
			<t2_node x="189.40002" y="111.80005" lid="573">
			<t2_node x="188.90002" y="111.19995" lid="570">
			<t2_node x="188.0" y="109.69995" lid="567">
			<t2_node x="188.5" y="108.599976" lid="564">
			<t2_node x="186.0" y="106.80005" lid="561">
			<t2_node x="184.5" y="105.80005" lid="558">
			<t2_node x="184.90002" y="103.599976" lid="555">
			<t2_node x="183.69995" y="100.30005" lid="552">
			<t2_node x="182.40002" y="99.900024" lid="549">
			<t2_node x="181.30005" y="99.099976" lid="546">
			<t2_node x="180.09998" y="98.0" lid="543">
			<t2_node x="179.59998" y="97.5" lid="540">
			<t2_node x="179.90002" y="96.69995" lid="537">
			<t2_node x="179.40002" y="96.400024" lid="534">
			<t2_node x="178.90002" y="95.900024" lid="531">
			<t2_node x="177.80005" y="94.69995" lid="528">
			<t2_node x="176.30005" y="93.400024" lid="525">
			<t2_node x="175.19995" y="92.900024" lid="522">
			<t2_node x="173.40002" y="91.69995" lid="519">
			<t2_node x="173.30005" y="91.69995" lid="516">
			<t2_node x="172.80005" y="91.0" lid="513">
			<t2_node x="171.90002" y="91.30005" lid="510">
			<t2_node x="169.90002" y="92.19995" lid="507">
			<t2_node x="168.80005" y="92.099976" lid="504">
			<t2_node x="167.59998" y="91.69995" lid="501">
			<t2_node x="165.69995" y="92.30005" lid="498">
			<t2_node x="163.5" y="92.599976" lid="495">
			<t2_node x="161.0" y="91.19995" lid="492">
			<t2_node x="157.69995" y="89.900024" lid="489">
			<t2_node x="156.69995" y="87.69995" lid="486">
			<t2_node x="156.09998" y="86.099976" lid="483">
			<t2_node x="156.30005" y="85.80005" lid="480">
			<t2_node x="155.59998" y="85.80005" lid="477">
			<t2_node x="157.69995" y="83.19995" lid="474">
			<t2_node x="157.59998" y="81.5" lid="471">
			<t2_node x="156.19995" y="80.5" lid="468">
			<t2_node x="153.5" y="80.5" lid="465">
			<t2_node x="151.80005" y="81.19995" lid="462">
			<t2_node x="151.30005" y="81.5" lid="459">
			<t2_node x="150.0" y="81.30005" lid="456">
			<t2_node x="148.19995" y="81.099976" lid="453">
			<t2_node x="147.0" y="80.099976" lid="450">
			<t2_node x="146.59998" y="78.599976" lid="447">
			<t2_node x="145.40002" y="79.30005" lid="444">
			<t2_node x="144.40002" y="79.30005" lid="441">
			<t2_node x="143.80005" y="79.19995" lid="438">
			<t2_node x="143.0" y="79.19995" lid="435">
			<t2_node x="141.80005" y="79.19995" lid="432">
			<t2_node x="140.19995" y="78.599976" lid="429">
			<t2_node x="138.59998" y="77.400024" lid="426">
			<t2_node x="137.0" y="77.0" lid="423">
			<t2_node x="135.40002" y="76.80005" lid="420">
			<t2_node x="136.5" y="75.599976" lid="417">
			<t2_node x="134.69995" y="74.5" lid="414">
			<t2_node x="132.90002" y="75.400024" lid="411">
			<t2_node x="131.90002" y="76.900024" lid="408">
			<t2_node x="130.09998" y="78.400024" lid="405">
			<t2_node x="129.0" y="78.599976" lid="402">
			<t2_node x="127.80005" y="78.0" lid="399">
			<t2_node x="128.19995" y="80.099976" lid="396">
			<t2_node x="128.09998" y="81.69995" lid="393">
			<t2_node x="127.30005" y="82.400024" lid="390">
			<t2_node x="124.69995" y="80.099976" lid="387">
			<t2_node x="123.900024" y="79.099976" lid="384">
			<t2_node x="123.400024" y="79.099976" lid="381">
			<t2_node x="123.599976" y="78.30005" lid="378">
			<t2_node x="123.5" y="78.599976" lid="375">
			<t2_node x="122.400024" y="78.19995" lid="372">
			<t2_node x="121.30005" y="77.80005" lid="369">
			<t2_node x="120.19995" y="77.400024" lid="366">
			<t2_node x="119.80005" y="77.099976" lid="363">
			<t2_node x="119.900024" y="77.099976" lid="360">
			<t2_node x="119.900024" y="78.0" lid="357">
			<t2_node x="119.30005" y="77.099976" lid="354">
			<t2_node x="118.900024" y="77.599976" lid="351">
			<t2_node x="118.0" y="76.69995" lid="348">
			<t2_node x="116.599976" y="74.599976" lid="345">
			<t2_node x="116.19995" y="74.69995" lid="342">
			 <t2_tag name="M1 input" key="1" />
			<t2_node x="113.900024" y="73.900024" lid="339">
			<t2_node x="112.80005" y="73.69995" lid="336">
			<t2_node x="110.900024" y="74.599976" lid="333">
			<t2_node x="109.099976" y="75.400024" lid="330">
			<t2_node x="109.19995" y="75.30005" lid="327">
			<t2_node x="107.30005" y="74.900024" lid="324">
			<t2_node x="106.30005" y="74.30005" lid="321">
			<t2_node x="106.0" y="73.400024" lid="318">
			<t2_node x="105.69995" y="73.19995" lid="315">
			<t2_node x="105.599976" y="73.0" lid="312">
			<t2_node x="104.099976" y="73.099976" lid="309">
			<t2_node x="103.400024" y="73.30005" lid="306">
			<t2_node x="102.599976" y="72.900024" lid="303">
			<t2_node x="101.5" y="72.69995" lid="300">
			<t2_node x="100.400024" y="72.599976" lid="297">
			<t2_node x="99.80005" y="72.400024" lid="294">
			<t2_node x="100.400024" y="72.099976" lid="291">
			<t2_node x="99.30005" y="70.599976" lid="288">
			<t2_node x="97.900024" y="68.900024" lid="285">
			<t2_node x="98.400024" y="68.599976" lid="282">
			<t2_node x="97.80005" y="69.80005" lid="279">
			<t2_node x="97.099976" y="70.599976" lid="276">
			<t2_node x="96.69995" y="70.900024" lid="273">
			<t2_node x="96.099976" y="69.80005" lid="270">
			<t2_node x="94.900024" y="69.099976" lid="267">
			<t2_node x="93.400024" y="68.400024" lid="264">
			<t2_node x="89.80005" y="66.80005" lid="264">
			<t2_node x="86.80005" y="61.900024" lid="264">
			<t2_node x="86.099976" y="54.400024" lid="264">
			<t2_node x="90.30005" y="48.0" lid="264" />
			</t2_node>
			<t2_node x="82.5" y="61.400024" lid="261">
			<t2_node x="80.0" y="61.19995" lid="258">
			<t2_node x="75.900024" y="61.5" lid="255">
			<t2_node x="75.099976" y="58.30005" lid="252">
			<t2_node x="76.099976" y="55.099976" lid="249">
			<t2_node x="76.19995" y="52.80005" lid="246">
			<t2_node x="75.599976" y="53.099976" lid="243">
			<t2_node x="75.5" y="51.69995" lid="240">
			<t2_node x="76.30005" y="52.599976" lid="237">
			<t2_node x="76.30005" y="52.19995" lid="234">
			<t2_node x="66.0" y="53.0" lid="234">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			</t2_node>
			</t2_node>
			<t2_node x="80.0" y="41.0" lid="240">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="79.0" y="41.0" lid="240">
			 <t2_tag name="POm input" key="2" />
			 </t2_node>
			<t2_node x="66.0" y="52.0" lid="240">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			</t2_node>
			<t2_node x="89.0" y="42.0" lid="243">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="67.0" y="52.0" lid="243">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			</t2_node>
			<t2_node x="70.0" y="52.0" lid="246">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="80.0" y="45.0" lid="246">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="95.0" y="44.0" lid="246">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			</t2_node>
			<t2_node x="78.0" y="48.0" lid="249">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			</t2_node>
			<t2_node x="68.0" y="55.0" lid="252">
			 <t2_tag name="M1 input" key="1" />
			 </t2_node>
			<t2_node x="68.0" y="54.0" lid="252">